profiles:
  0x01:  # Profile 1 configuration

    0x8001: # AP Capability Query message
      mandatory_tlvs: []
      optional_tlvs: []
    0x8002: # AP Capability Report message (17.1.7)
      mandatory_tlvs:
        - 0xA1 # AP Capability TLV
        - 0x85 # AP Radio Basic Capabilities TLV (one or more)
        - 0xCC # AKM Suite Capabilities TLV 
        - 0xA5 # Channel Scan Capabilities TLV
        - 0xA9 # Device 1905 Layer Security Capability TLV
        - 0xB2 # CAC Capabilities TLV
        - 0xB4 # Profile-2 AP Capability TLV
        - 0xC5 # Metric Collection Interval TLV
        - 0xD4 # Device Inventory TLV
        - 0x00 # End Of Message TLV
      optional_tlvs:
        - 0x86 # AP HT Capabilities TLV (zero or more)
        - 0x87 # AP VHT Capabilities TLV (zero or more)
        - 0x88 # AP HE Capabilities TLV (zero or more)
        - 0xAA # AP Wi-Fi 6 Capabilities TLV (zero or more)
        - 0xDF # Wi-Fi 7 Agent Capabilities TLV (TODO: verify hex code - zero or one)
        - 0xE7 # EHT Operations TLV (TODO: verify hex code - zero or one)
        - 0xBE # AP Radio Advanced Capabilities TLV (zero or more)

    0x000A: # AP-autoconfiguration renew message
      mandatory_tlvs:
        - 0x01 # 1905.1 AL MAC address TLV
        - 0x0F # Supported Role TLV
        - 0x10 # Supported Frequency Band TLV
        - 0x00 # End Of Message TLV
      optional_tlvs: []

    0x0007: # AP-autoconfiguration search message
      mandatory_tlvs:
        - 0x01 # 1905.1 AL MAC address TLV
        - 0x0D # Searched Role TLV
        - 0x0E # Autoconfig Frequency Band TLV
        - 0xB3 # Multi-AP Profile TLV
        - 0x00 # End Of Message TLV
      optional_tlvs:
        - 0x80 # SupportedService TLV
        - 0x81 # SearchedService TLV
        - 0xD3 # DPP Chirp Value TLV

    0x0008: # AP-autoconfiguration response message
      mandatory_tlvs:
        - 0x0F # Supported Role TLV
        - 0x10 # Supported Frequency Band TLV
        - 0xA9 # Device 1905 Layer Security Capability TLV
        - 0xB3 # Multi-AP Profile TLV
        - 0x00 # End Of Message TLV
      optional_tlvs:
        - 0x80 # SupportedService TLV
        - 0xDD # controller capability TLV
        - 0xD3 # DPP Chirp Value TLV

    0x0009: # AP-autoconfiguration WSC message
      # If sent by Multi-AP Agent (M1):
      agent_tlvs:
        mandatory_tlvs:
          - 0x11 # WSC TLV (containing M1)
          - 0x85 # AP Radio Basic Capabilities TLV
          - 0xB4 # Profile-2 AP Capability TLV
          - 0xBE # AP Radio Advanced Capabilities TLV
          - 0x00 # End Of Message TLV
        optional_tlvs: []
      # If sent by Multi-AP Controller (M2):
      controller_tlvs:
        mandatory_tlvs:
          - 0x11 # WSC TLV (containing M2)
          - 0x82 # AP Radio Identifier TLV
          - 0x00 # End Of Message TLV
        optional_tlvs:
          - 0xB5 # Default 802.1Q Settings TLV
          - 0xB6 # Traffic Separation Policy TLV
          - 0xE0 # Agent AP MLD Configuration TLV
          - 0xE1 # Backhaul STA MLD Configuration TLV.
          - 0xEB # RSN Parameters Configuration TLV
          - 0xEC # BSS Advanced Configuration TLV

    0x0000: # Topology Discovery message
      mandatory_tlvs:
        - 0x01 # 1905.1 AL MAC address type TLV
        - 0x02 # MAC address type TLV
        - 0x00 # End Of Message TLV
      optional_tlvs: []

    0x0002: # Topology Query message
      mandatory_tlvs:
        - 0xB3 # Multi-AP Profile TLV
        - 0x00 # End Of Message TLV
      optional_tlvs: []

    0x0001: # Topology Notification message
      mandatory_tlvs:
        - 0x01 # 1905.1 AL MAC address type TLV
        - 0x00 # End Of Message TLV
      optional_tlvs:
        - 0x92 # Client Association Event TLV (zero or one)

    0x0003: # Topology Response message
      mandatory_tlvs:
        - 0x03 # Device Information TLV
        - 0x83 # AP Operational BSS TLV
        - 0xB3 # Multi-AP Profile TLV
        - 0xB7 #BSS Configuration Report TLV
        - 0x00 # End Of Message TLV
      optional_tlvs:
        - 0x04 # Device Bridging Capability TLV
        - 0x06 # Non-1905 neighbor device list TLV
        - 0x07 # 1905.1 neighbor device list TLV
        - 0x80 # SupportedService TLV
        - 0x84 # Associated Clients TLV
        - 0xCB # Backhaul STA Radio Capabilities TLV.
        - 0xE0 # Agent AP MLD Configuration TLV
        - 0xE1 # Backhaul STA MLD Configuration TLV.
        - 0xE2 # Associated STA MLD Configuration TLV.
        - 0xE6 # TID-to-Link Mapping Policy TLV.

    0x8000: # 1905 ACK message
      mandatory_tlvs:
        - 0x00 # End Of Message TLV
      optional_tlvs:
        - 0xA3 # Error Code TLV

    0x8003: # Multi-AP Policy Config Request message (17.1.8)
      mandatory_tlvs:
        - 0x00 # End Of Message TLV
      optional_tlvs:
        - 0x89 # Steering Policy TLV
        - 0x8A # Metric Reporting Policy TLV
        - 0xB5 # Default 802.1Q Settings TLV
        - 0xB6 # Traffic Separation Policy TLV
        - 0xA4 # Channel Scan Reporting Policy TLV
        - 0xC4 # Unsuccessful Association Policy TLV
        - 0xD0 # Backhaul BSS Configuration TLV
        - 0xDB # QoS Management Policy TLV

    0x8004: # Channel Preference Query message
      mandatory_tlvs: []
      optional_tlvs: []

    0x8005: # Channel Preference Report message
      mandatory_tlvs:
        - 0xB1 # CAC Status Report TLV
        - 0x00 # End Of Message TLV
      optional_tlvs:
        - 0x8B # Channel Preference TLV
        - 0x8C # Radio Operation Restriction TLV
        - 0xAF # CAC Completion Report TLV
        - 0xE7 # EHT Operations TLV

    0x8006: # Channel Selection Request message
      mandatory_tlvs:
        - 0x00 # End Of Message TLV
      optional_tlvs:
        - 0x8B # Channel Preference TLV
        - 0x8D # Transmit Power Limit TLV
        - 0xD8 # Spatial Reuse Request TLV
        - 0xE7 # EHT Operations TLV

    0x8007: # Channel Selection Response message
      mandatory_tlvs:
        - 0x8E # Channel Selection Response TLV
        - 0x00 # End Of Message TLV
      optional_tlvs:
        - 0xDA # Spatial Reuse Config Response TLV
        - 0xBC # Profile-2 Error Code TLV.

    0x8008: # Operating Channel Report message
      mandatory_tlvs:
        - 0x8F # Operating Channel Report TLV
        - 0x00 # End Of Message TLV
      optional_tlvs:
        - 0xD9 # Spatial Reuse Report TLV
        - 0xE7 # EHT Operations TLV

  0x02:  # Profile 2 configuration
    0x8001: # AP Capability Query message
      mandatory_tlvs: []
      optional_tlvs: []
    0x8002: # AP Capability Report message (17.1.7)
      mandatory_tlvs:
        - 0xA1 # AP Capability TLV
        - 0x85 # AP Radio Basic Capabilities TLV (one or more)
        - 0xCC # AKM Suite Capabilities TLV 
        - 0xA5 # Channel Scan Capabilities TLV
        - 0xA9 # Device 1905 Layer Security Capability TLV
        - 0xB2 # CAC Capabilities TLV
        - 0xB4 # Profile-2 AP Capability TLV
        - 0xC5 # Metric Collection Interval TLV
        - 0xD4 # Device Inventory TLV
        - 0x00 # End Of Message TLV
      optional_tlvs:
        - 0x86 # AP HT Capabilities TLV (zero or more)
        - 0x87 # AP VHT Capabilities TLV (zero or more)
        - 0x88 # AP HE Capabilities TLV (zero or more)
        - 0xAA # AP Wi-Fi 6 Capabilities TLV (zero or more)
        - 0xDF # Wi-Fi 7 Agent Capabilities TLV (TODO: verify hex code - zero or one)
        - 0xE7 # EHT Operations TLV (TODO: verify hex code - zero or one)
        - 0xBE # AP Radio Advanced Capabilities TLV (zero or more)

    0x000A: # AP-autoconfiguration renew message
      mandatory_tlvs:
        - 0x01 # 1905.1 AL MAC address TLV
        - 0x0F # Supported Role TLV
        - 0x10 # Supported Frequency Band TLV
        - 0x00 # End Of Message TLV
      optional_tlvs: []

    0x0007: # AP-autoconfiguration search message
      mandatory_tlvs:
        - 0x01 # 1905.1 AL MAC address TLV
        - 0x0D # Searched Role TLV
        - 0x0E # Autoconfig Frequency Band TLV
        - 0xB3 # Multi-AP Profile TLV
        - 0x00 # End Of Message TLV
      optional_tlvs:
        - 0x80 # SupportedService TLV
        - 0x81 # SearchedService TLV
        - 0xD3 # DPP Chirp Value TLV

    0x0008: # AP-autoconfiguration response message
      mandatory_tlvs:
        - 0x0F # Supported Role TLV
        - 0x10 # Supported Frequency Band TLV
        - 0xA9 # Device 1905 Layer Security Capability TLV
        - 0xB3 # Multi-AP Profile TLV
        - 0x00 # End Of Message TLV
      optional_tlvs:
        - 0x80 # SupportedService TLV
        - 0xDD # controller capability TLV
        - 0xD3 # DPP Chirp Value TLV

    0x0009: # AP-autoconfiguration WSC message
      # If sent by Multi-AP Agent (M1):
      agent_tlvs:
        mandatory_tlvs:
          - 0x11 # WSC TLV (containing M1)
          - 0x85 # AP Radio Basic Capabilities TLV
          - 0xB4 # Profile-2 AP Capability TLV
          - 0xBE # AP Radio Advanced Capabilities TLV
          - 0x00 # End Of Message TLV
        optional_tlvs: []
      # If sent by Multi-AP Controller (M2):
      controller_tlvs:
        mandatory_tlvs:
          - 0x11 # WSC TLV (containing M2)
          - 0x82 # AP Radio Identifier TLV
          - 0x00 # End Of Message TLV
        optional_tlvs:
          - 0xB5 # Default 802.1Q Settings TLV
          - 0xB6 # Traffic Separation Policy TLV
          - 0xE0 # Agent AP MLD Configuration TLV
          - 0xE1 # Backhaul STA MLD Configuration TLV.
          - 0xEB # RSN Parameters Configuration TLV
          - 0xEC # BSS Advanced Configuration TLV

    0x0000: # Topology Discovery message
      mandatory_tlvs:
        - 0x01 # 1905.1 AL MAC address type TLV
        - 0x02 # MAC address type TLV
        - 0x00 # End Of Message TLV
      optional_tlvs: []

    0x0002: # Topology Query message
      mandatory_tlvs:
        - 0xB3 # Multi-AP Profile TLV
        - 0x00 # End Of Message TLV
      optional_tlvs: []

    0x0001: # Topology Notification message
      mandatory_tlvs:
        - 0x01 # 1905.1 AL MAC address type TLV
        - 0x00 # End Of Message TLV
      optional_tlvs:
        - 0x92 # Client Association Event TLV (zero or one)

    0x0003: # Topology Response message
      mandatory_tlvs:
        - 0x03 # Device Information TLV
        - 0x83 # AP Operational BSS TLV
        - 0xB3 # Multi-AP Profile TLV
        - 0xB7 #BSS Configuration Report TLV
        - 0x00 # End Of Message TLV
      optional_tlvs:
        - 0x04 # Device Bridging Capability TLV
        - 0x06 # Non-1905 neighbor device list TLV
        - 0x07 # 1905.1 neighbor device list TLV
        - 0x80 # SupportedService TLV
        - 0x84 # Associated Clients TLV
        - 0xCB # Backhaul STA Radio Capabilities TLV.
        - 0xE0 # Agent AP MLD Configuration TLV
        - 0xE1 # Backhaul STA MLD Configuration TLV.
        - 0xE2 # Associated STA MLD Configuration TLV.
        - 0xE6 # TID-to-Link Mapping Policy TLV.

    0x8000: # 1905 ACK message
      mandatory_tlvs:
        - 0x00 # End Of Message TLV
      optional_tlvs:
        - 0xA3 # Error Code TLV

    0x8003: # Multi-AP Policy Config Request message (17.1.8)
      mandatory_tlvs:
        - 0x00 # End Of Message TLV
      optional_tlvs:
        - 0x89 # Steering Policy TLV
        - 0x8A # Metric Reporting Policy TLV
        - 0xB5 # Default 802.1Q Settings TLV
        - 0xB6 # Traffic Separation Policy TLV
        - 0xA4 # Channel Scan Reporting Policy TLV
        - 0xC4 # Unsuccessful Association Policy TLV
        - 0xD0 # Backhaul BSS Configuration TLV
        - 0xDB # QoS Management Policy TLV

    0x8004: # Channel Preference Query message
      mandatory_tlvs: []
      optional_tlvs: []

    0x8005: # Channel Preference Report message
      mandatory_tlvs:
        - 0xB1 # CAC Status Report TLV
        - 0x00 # End Of Message TLV
      optional_tlvs:
        - 0x8B # Channel Preference TLV
        - 0x8C # Radio Operation Restriction TLV
        - 0xAF # CAC Completion Report TLV
        - 0xE7 # EHT Operations TLV

    0x8006: # Channel Selection Request message
      mandatory_tlvs:
        - 0x00 # End Of Message TLV
      optional_tlvs:
        - 0x8B # Channel Preference TLV
        - 0x8D # Transmit Power Limit TLV
        - 0xD8 # Spatial Reuse Request TLV
        - 0xE7 # EHT Operations TLV

    0x8007: # Channel Selection Response message
      mandatory_tlvs:
        - 0x8E # Channel Selection Response TLV
        - 0x00 # End Of Message TLV
      optional_tlvs:
        - 0xDA # Spatial Reuse Config Response TLV
        - 0xBC # Profile-2 Error Code TLV.

    0x8008: # Operating Channel Report message
      mandatory_tlvs:
        - 0x8F # Operating Channel Report TLV
        - 0x00 # End Of Message TLV
      optional_tlvs:
        - 0xD9 # Spatial Reuse Report TLV
        - 0xE7 # EHT Operations TLV

  0x03:  # Profile 3 configuration
    0x8001: # AP Capability Query message
      mandatory_tlvs: []
      optional_tlvs: []
    0x8002: # AP Capability Report message (17.1.7)
      mandatory_tlvs:
        - 0xA1 # AP Capability TLV
        - 0x85 # AP Radio Basic Capabilities TLV (one or more)
        - 0xCC # AKM Suite Capabilities TLV 
        - 0xA5 # Channel Scan Capabilities TLV
        - 0xA9 # Device 1905 Layer Security Capability TLV
        - 0xB2 # CAC Capabilities TLV
        - 0xB4 # Profile-2 AP Capability TLV
        - 0xC5 # Metric Collection Interval TLV
        - 0xD4 # Device Inventory TLV
        - 0x00 # End Of Message TLV
      optional_tlvs:
        - 0x86 # AP HT Capabilities TLV (zero or more)
        - 0x87 # AP VHT Capabilities TLV (zero or more)
        - 0x88 # AP HE Capabilities TLV (zero or more)
        - 0xAA # AP Wi-Fi 6 Capabilities TLV (zero or more)
        - 0xDF # Wi-Fi 7 Agent Capabilities TLV (TODO: verify hex code - zero or one)
        - 0xE7 # EHT Operations TLV (TODO: verify hex code - zero or one)
        - 0xBE # AP Radio Advanced Capabilities TLV (zero or more)

    0x000A: # AP-autoconfiguration renew message
      mandatory_tlvs:
        - 0x01 # 1905.1 AL MAC address TLV
        - 0x0F # Supported Role TLV
        - 0x10 # Supported Frequency Band TLV
        - 0x00 # End Of Message TLV
      optional_tlvs: []

    0x0007: # AP-autoconfiguration search message
      mandatory_tlvs:
        - 0x01 # 1905.1 AL MAC address TLV
        - 0x0D # Searched Role TLV
        - 0x0E # Autoconfig Frequency Band TLV
        - 0xB3 # Multi-AP Profile TLV
        - 0x00 # End Of Message TLV
      optional_tlvs:
        - 0x80 # SupportedService TLV
        - 0x81 # SearchedService TLV
        - 0xD3 # DPP Chirp Value TLV

    0x0008: # AP-autoconfiguration response message
      mandatory_tlvs:
        - 0x0F # Supported Role TLV
        - 0x10 # Supported Frequency Band TLV
        - 0xA9 # Device 1905 Layer Security Capability TLV
        - 0xB3 # Multi-AP Profile TLV
        - 0x00 # End Of Message TLV
      optional_tlvs:
        - 0x80 # SupportedService TLV
        - 0xDD # controller capability TLV
        - 0xD3 # DPP Chirp Value TLV

    0x0009: # AP-autoconfiguration WSC message
      # If sent by Multi-AP Agent (M1):
      agent_tlvs:
        mandatory_tlvs:
          - 0x11 # WSC TLV (containing M1)
          - 0x85 # AP Radio Basic Capabilities TLV
          - 0xB4 # Profile-2 AP Capability TLV
          - 0xBE # AP Radio Advanced Capabilities TLV
          - 0x00 # End Of Message TLV
        optional_tlvs: []
      # If sent by Multi-AP Controller (M2):
      controller_tlvs:
        mandatory_tlvs:
          - 0x11 # WSC TLV (containing M2)
          - 0x82 # AP Radio Identifier TLV
          - 0x00 # End Of Message TLV
        optional_tlvs:
          - 0xB5 # Default 802.1Q Settings TLV
          - 0xB6 # Traffic Separation Policy TLV
          - 0xE0 # Agent AP MLD Configuration TLV
          - 0xE1 # Backhaul STA MLD Configuration TLV.
          - 0xEB # RSN Parameters Configuration TLV
          - 0xEC # BSS Advanced Configuration TLV

    0x0000: # Topology Discovery message
      mandatory_tlvs:
        - 0x01 # 1905.1 AL MAC address type TLV
        - 0x02 # MAC address type TLV
        - 0x00 # End Of Message TLV
      optional_tlvs: []

    0x0002: # Topology Query message
      mandatory_tlvs:
        - 0xB3 # Multi-AP Profile TLV
        - 0x00 # End Of Message TLV
      optional_tlvs: []

    0x0001: # Topology Notification message
      mandatory_tlvs:
        - 0x01 # 1905.1 AL MAC address type TLV
        - 0x00 # End Of Message TLV
      optional_tlvs:
        - 0x92 # Client Association Event TLV (zero or one)

    0x0003: # Topology Response message
      mandatory_tlvs:
        - 0x03 # Device Information TLV
        - 0x83 # AP Operational BSS TLV
        - 0xB3 # Multi-AP Profile TLV
        - 0xB7 #BSS Configuration Report TLV
        - 0x00 # End Of Message TLV
      optional_tlvs:
        - 0x04 # Device Bridging Capability TLV
        - 0x06 # Non-1905 neighbor device list TLV
        - 0x07 # 1905.1 neighbor device list TLV
        - 0x80 # SupportedService TLV
        - 0x84 # Associated Clients TLV
        - 0xCB # Backhaul STA Radio Capabilities TLV.
        - 0xE0 # Agent AP MLD Configuration TLV
        - 0xE1 # Backhaul STA MLD Configuration TLV.
        - 0xE2 # Associated STA MLD Configuration TLV.
        - 0xE6 # TID-to-Link Mapping Policy TLV.

    0x8000: # 1905 ACK message
      mandatory_tlvs:
        - 0x00 # End Of Message TLV
      optional_tlvs:
        - 0xA3 # Error Code TLV

    0x8003: # Multi-AP Policy Config Request message (17.1.8)
      mandatory_tlvs:
        - 0x00 # End Of Message TLV
      optional_tlvs:
        - 0x89 # Steering Policy TLV
        - 0x8A # Metric Reporting Policy TLV
        - 0xB5 # Default 802.1Q Settings TLV
        - 0xB6 # Traffic Separation Policy TLV
        - 0xA4 # Channel Scan Reporting Policy TLV
        - 0xC4 # Unsuccessful Association Policy TLV
        - 0xD0 # Backhaul BSS Configuration TLV
        - 0xDB # QoS Management Policy TLV

    0x8004: # Channel Preference Query message
      mandatory_tlvs: []
      optional_tlvs: []

    0x8005: # Channel Preference Report message
      mandatory_tlvs:
        - 0xB1 # CAC Status Report TLV
        - 0x00 # End Of Message TLV
      optional_tlvs:
        - 0x8B # Channel Preference TLV
        - 0x8C # Radio Operation Restriction TLV
        - 0xAF # CAC Completion Report TLV
        - 0xE7 # EHT Operations TLV

    0x8006: # Channel Selection Request message
      mandatory_tlvs:
        - 0x00 # End Of Message TLV
      optional_tlvs:
        - 0x8B # Channel Preference TLV
        - 0x8D # Transmit Power Limit TLV
        - 0xD8 # Spatial Reuse Request TLV
        - 0xE7 # EHT Operations TLV

    0x8007: # Channel Selection Response message
      mandatory_tlvs:
        - 0x8E # Channel Selection Response TLV
        - 0x00 # End Of Message TLV
      optional_tlvs:
        - 0xDA # Spatial Reuse Config Response TLV
        - 0xBC # Profile-2 Error Code TLV.

    0x8008: # Operating Channel Report message
      mandatory_tlvs:
        - 0x8F # Operating Channel Report TLV
        - 0x00 # End Of Message TLV
      optional_tlvs:
        - 0xD9 # Spatial Reuse Report TLV
        - 0xE7 # EHT Operations TLV
  