controller:
  ip: ""
  user: ""

extenders:
  ext1:
    enabled: <True/False>
    ip: ""
    user: ""
  ext2:
    enabled: <True/False>
    ip: ""
    user: ""
    
wifi_clients:
  client1:
    enabled: <True/False>
    ip: ""
    user:  ""
    pass: ""

lan_clients:
  lan1:
    enabled: <True/False>
    mac: ""
    user: ""
    pass: ""

database:
  name: OneWifiMesh
  user: ""
  pass: ""
  ssid_table: NetworkSSIDList

system:
  bridge_intf: brlan0
  wifi_reset_interface: eth0_virt_peer
  reset_json_file: /usr/ccsp/EasyMesh/Reset.json
